keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: geojsonapp
  ssl-required: external
  resource: app-geojson
  credentials:
    secret: secret
  bearer-only: true

server:
  port : 8081
  
spring:
  application:
    name: geojsonapp
